
###
###注册接口
POST http://127.0.0.1:8081/signup
Content-Type: application/json

{
  "username": "test_go2",
  "password": "1234",
  "re_password": "1234"
}


###登录接口
POST http://127.0.0.1:8081/login
Content-Type: application/json

{
  "username": "test_go2",
  "password": "1234",
  "token": "my-secret-token"
}

###登录接口
POST http://127.0.0.1:8081/ping
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxNDE3NDAxMzQ3MzIxMzY4NTc2LCJ1c2VybmFtZSI6InRlc3RfZ28yIiwiZXhwIjoxNjI2ODQzOTgzLCJpc3MiOiJteS1wcm9qZWN0In0.VF0PpLAKOPzxQIJ8zx3OCFuzqciptLOF-wAd6gi6BUA

{
  "username": "test_go2",
  "password": "1234",
}
