
###
###注册接口
POST http://127.0.0.1:8081/signup
Content-Type: application/json

{
  "username": "test_go4",
  "password": "123456",
  "re_password": "123456"
}

###登录接口
POST http://127.0.0.1:8081/login
Content-Type: application/json

{
  "username": "test_go2",
  "password": "1234"
}

###获取社区数据
GET http://127.0.0.1:8081/api/v1/community
Authorization: Bearer {{token}}

{
  "": ""
}

###根据社区id，获取详情数据
GET http://127.0.0.1:8081/api/v1/community/2
Authorization: Bearer {{token}}

{
  "": ""
}

###添加帖子
POST http://127.0.0.1:8081/api/v1/post
Authorization: Bearer {{token}}

{
  "CommunityID": 1,
  "Status": 1,
  "Title": "雄鹿夺冠了",
  "Content": "7.21号，雄鹿夺冠了，字母哥屌炸了",
}

